### ISSUE TITLE
Address TODO in ctf/core.py:32

### ISSUE THREAD

**Issue by nickago** [WhiteHatCP/wrath-ctf-framework#16]
Even if it's just to remove it

**Comment by DeltaHeavy** [comment]
For reference

**Comment by DeltaHeavy** [comment]
Should it be? I leave this up to our friendly neighborhood SQLAlchemist and DBA, Nick and Nick, respectively

**Comment by nickfrostatx** [comment]
This is a pretty classical atomicity problem. Enter two flegs at the same time, and your read-update-write will only add one of them to your score. Since the score is just a sum of your flegs anyway, we should reflect that in the implementation.

(Now, if someone actually enters two flegs at the same time, they're probably cheating.)

**Comment by nickfrostatx** [comment]
This is potentially closed by #26.

**Comment by DeltaHeavy** [comment]
Close with #26
