### ISSUE TITLE
No more static data in the database

### ISSUE THREAD

**Issue by atti1a** [WhiteHatCP/wrath-ctf-framework#43]
BIG CHANGE
We should probably have all the config data just stored in memory, instead of all kept in the database where it doesn't need to be.

**Comment by nickfrostatx** [comment]
As @atti1a pointed out out-of-band, this would break our database.

We'd no longer get foreign keys to challenges. "Problem solve" records would contain some ID for the challenge, but not an ID in the database. It would have to be some ID that comes from ``ctf.json``. So anything we want to do with challenge data in queries (grouping by category, or totaling up team scores and sorting by that) we'd have to do ourselves in Python instead of having our database do it for us.

If we do that, we also lose the ability to run meaningful queries against the database during the competition. Moving challenges from the database to the app instance requires that you have access to the database, and to app (and ``ctf.json``) in order to do anything. No longer could we just whip out a read-only SQL shell and start looking at data.

**Comment by nickfrostatx** [comment]
The proposed change doesn't actually remove static data from the database, it just keeps that up to date (tracked in #46). Closing.
